// Code generated by scripts/generate-terminal-contract-bindings.mjs. DO NOT EDIT.

package protocol

const (
	WireContractVersion = 1
	MinDimension        = 1
	MaxDimension        = 2000
)

const (
	SessionsHTTPRoute = "/api/sessions"
	TerminalWSRoute   = "/api/terminal"
)

const (
	ClientMessageTypeAttach = "attach"
	ClientMessageTypeInput  = "input"
	ClientMessageTypeResize = "resize"
	ClientMessageTypePing   = "ping"
)

const (
	ServerMessageTypeReady  = "ready"
	ServerMessageTypeOutput = "output"
	ServerMessageTypeExit   = "exit"
	ServerMessageTypeError  = "error"
	ServerMessageTypePong   = "pong"
)

const (
	ServerErrorCodeSessionNotFound     = "session_not_found"
	ServerErrorCodeAttachForbidden     = "attach_forbidden"
	ServerErrorCodeIncompatibleVersion = "incompatible_version"
	ServerErrorCodeAttachRequired      = "attach_required"
	ServerErrorCodeReadOnlyForbidden   = "read_only_forbidden"
	ServerErrorCodeSessionNotWritable  = "session_not_writable"
	ServerErrorCodeSessionNotResizable = "session_not_resizable"
)

const UnknownServerErrorCodePolicy = "preserve_raw_code"

var ClientMessageTypes = []string{
	"attach",
	"input",
	"resize",
	"ping",
}

var ServerMessageTypes = []string{
	"ready",
	"output",
	"exit",
	"error",
	"pong",
}

var KnownServerErrorCodes = []string{
	"session_not_found",
	"attach_forbidden",
	"incompatible_version",
	"attach_required",
	"read_only_forbidden",
	"session_not_writable",
	"session_not_resizable",
}

const SessionsEnvelopeField = "sessions"

var SessionSnapshotRequiredFields = []string{
	"id",
	"hasController",
	"canControl",
	"watchers",
	"createdAtMs",
	"lastActivityMs",
}

var SessionSnapshotOptionalFields = []string{
	"command",
}
