// Code generated by scripts/generate-terminal-contract-bindings.mjs. DO NOT EDIT.

export const TERMINAL_WIRE_CONTRACT_VERSION = 1 as const;

export const TERMINAL_DIMENSION_LIMIT = {
  MIN: 1,
  MAX: 2000,
} as const;

export const TERMINAL_BACKEND_ROUTE = {
  SESSIONS_HTTP: "/api/sessions",
  TERMINAL_WS: "/api/terminal",
} as const;

export const TERMINAL_CLIENT_MESSAGE_TYPE = {
  ATTACH: "attach",
  INPUT: "input",
  RESIZE: "resize",
  PING: "ping",
} as const;

export const TERMINAL_SERVER_MESSAGE_TYPE = {
  READY: "ready",
  OUTPUT: "output",
  EXIT: "exit",
  ERROR: "error",
  PONG: "pong",
} as const;

export const TERMINAL_SERVER_ERROR_CODE = {
  SESSION_NOT_FOUND: "session_not_found",
  ATTACH_FORBIDDEN: "attach_forbidden",
  INCOMPATIBLE_VERSION: "incompatible_version",
  ATTACH_REQUIRED: "attach_required",
  READ_ONLY_FORBIDDEN: "read_only_forbidden",
  SESSION_NOT_WRITABLE: "session_not_writable",
  SESSION_NOT_RESIZABLE: "session_not_resizable",
} as const;

export const TERMINAL_SERVER_ERROR_CODES = [
  "session_not_found",
  "attach_forbidden",
  "incompatible_version",
  "attach_required",
  "read_only_forbidden",
  "session_not_writable",
  "session_not_resizable",
] as const;

export const TERMINAL_UNKNOWN_SERVER_ERROR_POLICY =
  "preserve_raw_code" as const;

export const SESSIONS_ENVELOPE_FIELD = "sessions" as const;

export const SESSION_SNAPSHOT_REQUIRED_FIELDS = [
  "id",
  "hasController",
  "canControl",
  "watchers",
  "createdAtMs",
  "lastActivityMs",
] as const;

export const SESSION_SNAPSHOT_OPTIONAL_FIELDS = ["command"] as const;
