import {
  TERMINAL_SERVER_ERROR_CODES as GENERATED_TERMINAL_SERVER_ERROR_CODES,
  TERMINAL_SERVER_ERROR_CODE,
  TERMINAL_UNKNOWN_SERVER_ERROR_POLICY,
} from "./generated-wire-contract";
export { TERMINAL_SERVER_ERROR_CODE };

export type TerminalServerErrorCode =
  (typeof TERMINAL_SERVER_ERROR_CODE)[keyof typeof TERMINAL_SERVER_ERROR_CODE];

export const TERMINAL_SERVER_ERROR_CODES =
  GENERATED_TERMINAL_SERVER_ERROR_CODES;

export const UNKNOWN_SERVER_ERROR_CODE_POLICY =
  TERMINAL_UNKNOWN_SERVER_ERROR_POLICY;
